name: Medication Reminder Bot

on:
  schedule:
    - cron: '25 15 * * *'  # 8:55 PM IST (3:25 PM UTC) - Evening Reminder

jobs:
  evening-reminder:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allow the workflow to write to the repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-telegram-bot

      - name: Send Evening Reminder
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python medication_reminder.py

      - name: Commit updated message_index.txt
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git pull
          git add message_index.txt
          git commit -m "Update message_index.txt" || echo "No changes to commit"
          git push
